version: '3.4'

services:
  fiapreservas.webapi: &api
    build:
      context: .
      dockerfile: FiapReservas.WebAPI/Dockerfile
    environment:
      - NOME=API1
      - ASPNETCORE_ENVIRONMENT=development
    ports:
      - "5001:8080"
  fiapreservas.webapi2:
    <<: *api
    ports:
      - "5002:8080"
    environment:
      - NOME=API2
      - ASPNETCORE_ENVIRONMENT=development
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fiapreservas.webapi
      - fiapreservas.webapi2
    ports:
      - "9999:9999"